export const siteConfig = {
  basePath: '/texassolver_gpu_page',
  productName: 'TexasSolver GPU',
  email: 'icybee@yeah.net',
  contactHref: 'mailto:icybee@yeah.net',
  discordHref: 'https://discord.com/invite/RtyD4vRy2e',
  githubHref: 'https://github.com/bupticybee/TexasSolverGPU',
  downloadHref: 'https://github.com/bupticybee/TexasSolverGPU/releases',
  tutorialHref: 'https://www.youtube.com/watch?v=jAI_yudEGJw&list=PLKQz8vKPRvhmWz8lOUZjeLo7GQyG2ebu-',
  screenshots: {
    logo: 'logo-mark.png',
    tree: 'tree_construction_page.png',
    quickStart: 'quick_start_page.png',
    nodeLock: 'node_lock_page.png',
    batch: 'batch_solving_page.png',
    play: 'play_against_strategy.png',
  },
}

export const localeLabels = {
  en: 'English',
  zh: '中文',
  ko: '한국어',
  ja: '日本語',
  ru: 'Русский',
}

export const localeOrder = ['en', 'zh', 'ko', 'ja', 'ru']

export const localizedContent = {
  en: {
    lang: 'en',
    title: 'TexasSolver GPU | GPU Poker Solver Workspace',
    description:
      'TexasSolver GPU is the world’s first GPU solver for poker, completely free for personal use, with faster solving, node locking, batch analysis, and play-vs-strategy training.',
    nav: { overview: 'Overview', features: 'Features', faq: 'FAQ', language: 'Language' },
    hero: {
      eyebrow: 'Completely free for personal use',
      title: 'The world’s first GPU solver for poker',
      description:
        'TexasSolver GPU is built for faster solving, quick spot entry, batch analysis, node locking, and strategy training in one focused workspace.',
      download: 'Download for Free',
      tutorial: 'Video Tutorial',
      discord: 'Join Discord',
      contact: 'Contact',
      platform: 'Windows Only',
      free: 'Free for Personal Use',
      claim: 'The world’s first GPU solver',
    },
    valuesTitle: 'GPU changes the speed ceiling',
    valuesText: 'Built on GPU computing, TexasSolver GPU is faster than the solver workflows that came before it.',
    values: [
      ['Faster Than Previous Solvers', 'Built on GPU computing, TexasSolver GPU reaches results faster than the solver workflows players were used to before.'],
      ['Completely Free for Personal Use', 'Download it, explore the workflow, and start studying without a paywall for personal use.'],
      ['Serious Research Workflow', 'Move quickly from setup to analysis with tree configuration, batch solving, node locking, and training tools in one place.'],
      ['Solve at Scale', 'Run multiple boards in one batch-oriented flow and keep progress visible while you work.'],
    ],
    featuresTitle: 'Five product views that show the whole workflow',
    featuresText: 'See the actual product workflow through tree configuration, node locking, batch solving, and strategy training.',
    ecosystemTitle: 'Fits the way people actually study',
    ecosystemText:
      'TexasSolver GPU supports open data formats, readable data scripts, and range imports that make it easier to fit into surrounding study setups.',
    ecosystem: ['Open data formats', 'Readable data scripts', 'Range import support', 'Friendly to external workflows'],
    futureTitle: 'And this is only the beginning',
    futureText:
      'Behind TexasSolver GPU, we are already building even faster methods, deeper optimizations, and much more ambitious solver technology.',
    faqTitle: 'FAQ',
    faq: [
      ['What platform is supported?', 'The current release is built for Windows.'],
      ['Is it free for personal use?', 'Yes. TexasSolver GPU is completely free for personal use.'],
      ['Where should I go for questions or updates?', 'Use the Discord server for community discussion or contact directly by email.'],
      ['Can it fit into other tools?', 'Yes. TexasSolver GPU supports open data formats, readable scripts, and range imports.'],
    ],
    footer: { rights: 'All rights reserved.', github: 'GitHub', discord: 'Join Discord', contact: 'Contact' },
  },
  zh: {
    lang: 'zh-CN',
    title: 'TexasSolver GPU | GPU 德扑求解工作台',
    description:
      'TexasSolver GPU 是世界第一个德州扑克 GPU Solver，对个人完全免费，并提供更快求解、Node Lock、批量分析和与策略对战训练。',
    nav: { overview: '概览', features: '功能', faq: '常见问题', language: '语言' },
    hero: {
      eyebrow: '对个人完全免费',
      title: '世界第一个德州扑克 GPU Solver',
      description:
        'TexasSolver GPU 把更快求解、快速进入场景、批量分析、Node Lock 和训练工具整合到同一套研究体验中。',
      download: '免费下载',
      tutorial: '视频教程',
      discord: '加入 Discord',
      contact: '联系我',
      platform: '仅支持 Windows',
      free: '对个人完全免费',
      claim: '世界第一个 GPU Solver',
    },
    valuesTitle: 'GPU 直接改变了求解速度上限',
    valuesText: '建立在 GPU 计算之上，TexasSolver GPU 的速度比以往的 solver 工作流都更快。',
    values: [
      ['比以往 Solver 更快', '因为直接建立在 GPU 计算之上，TexasSolver GPU 的求解速度比玩家过去习惯的 solver 工作流都更快。'],
      ['对个人完全免费', '个人用户可以直接下载、体验和进入研究流程，不需要先跨过付费门槛。'],
      ['完整研究工作流', '把树构建、批量分析、Node Lock 和训练工具放进同一套研究体验里。'],
      ['批量分析能力', '在一个批量工作流里处理多个 board，并清晰看到进度。'],
    ],
    featuresTitle: '用 5 个真实界面讲完整个工作流',
    featuresText: '通过树构建、Node Lock、批量分析和训练模块，直接看到真实产品工作流。',
    ecosystemTitle: '更贴近真实研究方式',
    ecosystemText: 'TexasSolver GPU 支持开放数据格式、可读取数据脚本和 range 导入，更容易接入你已有的研究流程。',
    ecosystem: ['开放数据格式', '可读取数据脚本', '支持导入 range', '方便接入外部工作流'],
    futureTitle: '而这还只是开始',
    futureText: '在 TexasSolver GPU 背后，我们已经在推进更快的方法、更深的优化，以及更激进的新一代求解技术。',
    faqTitle: '常见问题',
    faq: [
      ['支持什么平台？', '当前版本面向 Windows。'],
      ['对个人使用免费吗？', '是的，TexasSolver GPU 对个人完全免费。'],
      ['去哪里提问或获取更新？', '可以加入 Discord，或通过邮件直接联系。'],
      ['能和其他工具配合吗？', '可以，TexasSolver GPU 支持开放数据格式、可读取脚本和 range 导入。'],
    ],
    footer: { rights: '保留所有权利。', github: 'GitHub', discord: '加入 Discord', contact: '联系我' },
  },
  ko: {
    lang: 'ko',
    title: 'TexasSolver GPU | GPU 포커 솔버 워크스페이스',
    description:
      'TexasSolver GPU는 포커를 위한 세계 최초의 GPU 솔버이며, 개인 사용 완전 무료로 더 빠른 계산, 노드 락, 배치 분석, 전략 훈련을 제공합니다.',
    nav: { overview: '개요', features: '기능', faq: 'FAQ', language: '언어' },
    hero: {
      eyebrow: '개인 사용 완전 무료',
      title: '포커를 위한 세계 최초의 GPU 솔버',
      description:
        'TexasSolver GPU는 더 빠른 계산, 빠른 시나리오 진입, 배치 분석, 노드 락, 전략 훈련을 하나의 워크스페이스로 묶습니다.',
      download: '무료 다운로드',
      tutorial: '동영상 튜토리얼',
      discord: '디스코드 참여',
      contact: '문의하기',
      platform: 'Windows 전용',
      free: '개인 사용 완전 무료',
      claim: '세계 최초의 GPU 솔버',
    },
    valuesTitle: 'GPU가 계산 속도의 상한을 바꿉니다',
    valuesText: 'GPU 계산을 기반으로 한 TexasSolver GPU는 이전 세대의 솔버 워크플로보다 더 빠릅니다.',
    values: [
      ['기존 솔버보다 더 빠름', 'GPU 계산을 직접 활용하기 때문에, TexasSolver GPU는 플레이어가 익숙했던 이전 솔버 워크플로보다 더 빠르게 결과에 도달합니다.'],
      ['개인 사용 완전 무료', '개인 사용자는 비용 부담 없이 바로 다운로드하고 연구 워크플로를 시작할 수 있습니다.'],
      ['완전한 연구 워크플로', '트리 구성, 배치 분석, 노드 락, 훈련 도구를 하나의 연구 경험으로 묶었습니다.'],
      ['배치 분석', '여러 보드를 하나의 작업 흐름에서 처리하고 진행 상황을 계속 확인할 수 있습니다.'],
    ],
    featuresTitle: '전체 워크플로를 보여주는 5개의 실제 화면',
    featuresText: '트리 구성, 노드 락, 배치 분석, 전략 훈련까지 실제 제품 워크플로를 직접 보여줍니다.',
    ecosystemTitle: '실제 연구 방식에 잘 맞는 설계',
    ecosystemText: '오픈 데이터 포맷, 읽기 쉬운 데이터 스크립트, 레인지 가져오기를 통해 기존 연구 흐름과 자연스럽게 연결됩니다.',
    ecosystem: ['오픈 데이터 포맷', '읽기 쉬운 데이터 스크립트', '레인지 가져오기', '외부 워크플로 친화적'],
    futureTitle: '그리고 이것은 시작에 불과합니다',
    futureText: 'TexasSolver GPU 뒤에서는 더 빠른 방법론, 더 깊은 최적화, 그리고 훨씬 더 공격적인 차세대 솔버 기술이 계속 개발되고 있습니다.',
    faqTitle: 'FAQ',
    faq: [
      ['어떤 플랫폼을 지원하나요?', '현재 릴리스는 Windows용입니다.'],
      ['개인 사용은 무료인가요?', '네. TexasSolver GPU는 개인 사용 완전 무료입니다.'],
      ['질문이나 업데이트는 어디서 확인하나요?', '디스코드에 참여하거나 이메일로 직접 문의할 수 있습니다.'],
      ['다른 도구와 함께 쓸 수 있나요?', '네. TexasSolver GPU는 오픈 데이터 포맷, 읽기 쉬운 스크립트, 레인지 가져오기를 지원합니다.'],
    ],
    footer: { rights: '모든 권리 보유.', github: 'GitHub', discord: '디스코드 참여', contact: '문의하기' },
  },
  ja: {
    lang: 'ja',
    title: 'TexasSolver GPU | GPU ポーカーソルバーワークスペース',
    description:
      'TexasSolver GPU はポーカー向け世界初の GPU solver で、個人利用完全無料。高速計算、Node Lock、バッチ分析、戦略練習をまとめます。',
    nav: { overview: '概要', features: '機能', faq: 'FAQ', language: '言語' },
    hero: {
      eyebrow: '個人利用は完全無料',
      title: 'ポーカー向け世界初の GPU solver',
      description:
        'TexasSolver GPU は高速計算、シナリオ選択、バッチ分析、Node Lock、戦略トレーニングをひとつの研究体験にまとめます。',
      download: '無料ダウンロード',
      tutorial: 'ビデオチュートリアル',
      discord: 'Discord に参加',
      contact: 'お問い合わせ',
      platform: 'Windows 専用',
      free: '個人利用完全無料',
      claim: '世界初の GPU solver',
    },
    valuesTitle: 'GPU が計算速度の上限を引き上げる',
    valuesText: 'GPU 計算を前提にした TexasSolver GPU は、これまでの solver ワークフローよりも速く結果に到達します。',
    values: [
      ['従来 solver より速い', 'GPU 計算を直接活かすことで、従来の solver ワークフローよりも速く結果へ到達できます。'],
      ['個人利用完全無料', '個人ユーザーは料金を気にせずにダウンロードして、すぐ研究を始められます。'],
      ['完全な研究ワークフロー', 'ツリー構築、バッチ分析、Node Lock、戦略トレーニングを 1 つの研究体験にまとめます。'],
      ['バッチ分析', '複数のボードを 1 つの流れで処理し、進捗も見やすく保てます。'],
    ],
    featuresTitle: '実際のワークフローを見せる 5 つの画面',
    featuresText: 'ツリー構築、Node Lock、バッチ分析、戦略練習まで、実際の製品ワークフローをそのまま確認できます。',
    ecosystemTitle: '実際の研究スタイルにフィット',
    ecosystemText: 'オープンなデータ形式、読みやすいデータスクリプト、レンジのインポートにより既存の研究環境にも組み込みやすくなります。',
    ecosystem: ['オープンなデータ形式', '読みやすいデータスクリプト', 'レンジのインポート', '外部ワークフローと親和性'],
    futureTitle: 'そして、これはまだ始まりにすぎません',
    futureText: 'TexasSolver GPU の背後では、さらに高速な手法、より深い最適化、そして次世代の solver 技術をすでに開発し続けています。',
    faqTitle: 'FAQ',
    faq: [
      ['対応プラットフォームは？', '現在のリリースは Windows 向けです。'],
      ['個人利用は無料ですか？', 'はい。TexasSolver GPU は個人利用完全無料です。'],
      ['質問や更新はどこで確認できますか？', 'Discord に参加するか、メールで直接連絡できます。'],
      ['他のツールと連携できますか？', 'はい。TexasSolver GPU はオープンなデータ形式、読みやすいスクリプト、レンジのインポートをサポートします。'],
    ],
    footer: { rights: 'All rights reserved.', github: 'GitHub', discord: 'Discord に参加', contact: 'お問い合わせ' },
  },
  ru: {
    lang: 'ru',
    title: 'TexasSolver GPU | GPU рабочее пространство для покера',
    description:
      'TexasSolver GPU — это первый в мире GPU solver для покера, полностью бесплатный для личного использования, с быстрыми расчетами, node lock, пакетным анализом и тренировкой.',
    nav: { overview: 'Обзор', features: 'Функции', faq: 'FAQ', language: 'Язык' },
    hero: {
      eyebrow: 'Полностью бесплатно для личного использования',
      title: 'Первый в мире GPU solver для покера',
      description:
        'TexasSolver GPU объединяет быстрые расчеты, быстрый вход в сценарии, пакетный анализ, node lock и тренировку в одном исследовательском процессе.',
      download: 'Скачать бесплатно',
      tutorial: 'Видеоурок',
      discord: 'Войти в Discord',
      contact: 'Связаться',
      platform: 'Только Windows',
      free: 'Полностью бесплатно для личного использования',
      claim: 'Первый в мире GPU solver',
    },
    valuesTitle: 'GPU поднимает верхнюю планку скорости',
    valuesText: 'Построенный на GPU-вычислениях, TexasSolver GPU работает быстрее, чем привычные solver-процессы прошлого поколения.',
    values: [
      ['Быстрее прежних solver', 'За счет прямого использования GPU TexasSolver GPU приходит к результатам быстрее, чем solver-процессы, к которым игроки привыкли раньше.'],
      ['Полностью бесплатно для личного использования', 'Личные пользователи могут сразу скачать продукт и начать работать без платного барьера.'],
      ['Полный исследовательский процесс', 'Настройка дерева, пакетный анализ, node lock и тренировка собраны в одном рабочем процессе.'],
      ['Пакетный анализ', 'Обрабатывайте несколько бордов в одном потоке и всегда видьте прогресс работы.'],
    ],
    featuresTitle: 'Пять экранов, которые показывают весь рабочий процесс',
    featuresText: 'Покажите реальный рабочий процесс: настройку дерева, node lock, пакетный анализ и тренировку против стратегии.',
    ecosystemTitle: 'Подходит для реального учебного процесса',
    ecosystemText: 'Открытые форматы данных, читаемые скрипты и импорт диапазонов помогают встроить TexasSolver GPU в существующие исследовательские процессы.',
    ecosystem: ['Открытые форматы данных', 'Читаемые скрипты данных', 'Импорт диапазонов', 'Подходит для внешних рабочих процессов'],
    futureTitle: 'И это только начало',
    futureText: 'За TexasSolver GPU уже стоят еще более быстрые методы, более глубокие оптимизации и гораздо более амбициозные solver-технологии следующего поколения.',
    faqTitle: 'FAQ',
    faq: [
      ['Какая платформа поддерживается?', 'Текущий релиз предназначен для Windows.'],
      ['Бесплатно ли это для личного использования?', 'Да. TexasSolver GPU полностью бесплатен для личного использования.'],
      ['Где задавать вопросы и следить за обновлениями?', 'Можно присоединиться к Discord или написать напрямую по email.'],
      ['Можно ли встроить в другие инструменты?', 'Да. TexasSolver GPU поддерживает открытые форматы данных, читаемые скрипты и импорт диапазонов.'],
    ],
    footer: { rights: 'Все права защищены.', github: 'GitHub', discord: 'Войти в Discord', contact: 'Связаться' },
  },
}

export const featureOrder = ['tree', 'nodeLock', 'play', 'quickStart', 'batch']

export const featureContent = {
  tree: {
    en: ['Flexible Tree Configuration', 'Core workspace', 'Set board, pot, stacks, ranges, and sizings from one focused view that establishes the product as a serious analysis tool.'],
    zh: ['灵活树构建', '核心工作台', '在一个专注的界面中设定牌面、底池、筹码、范围和下注结构，直接建立专业工具感。'],
    ko: ['유연한 트리 구성', '핵심 워크스페이스', '보드, 팟, 스택, 레인지, 사이징을 하나의 화면에서 다루며 제품의 전문성을 바로 보여줍니다.'],
    ja: ['柔軟なツリー構築', 'コアワークスペース', 'ボード、ポット、スタック、レンジ、サイズを 1 つの画面で扱い、製品の専門性を印象付けます。'],
    ru: ['Гибкая настройка дерева', 'Ключевое рабочее пространство', 'Настраивайте борд, пот, стеки, диапазоны и сайзинги в одном представлении, которое сразу показывает профессиональный уровень инструмента.'],
  },
  nodeLock: {
    en: ['Visual Node Lock', 'Flagship feature', 'Adjust frequencies visually, apply locks by class, and re-solve with a workflow that feels built for real analysis sessions.'],
    zh: ['可视化 Node Lock', '重点能力', '用可视化方式调整频率、按类别应用锁定并重求解，更贴近真实分析流程。'],
    ko: ['비주얼 노드 락', '대표 기능', '빈도를 시각적으로 조정하고 클래스별로 락을 적용한 뒤 다시 계산할 수 있어 실제 분석 흐름에 잘 맞습니다.'],
    ja: ['ビジュアル Node Lock', '代表機能', '頻度を視覚的に調整し、クラス単位でロックを適用して再計算できるため、実際の分析作業に自然に馴染みます。'],
    ru: ['Визуальный Node Lock', 'Флагманская функция', 'Визуально меняйте частоты, применяйте блокировки по классам и пересчитывайте дерево в рабочем процессе, ориентированном на реальный анализ.'],
  },
  play: {
    en: ['Play Vs Strategy', 'Training loop', 'Train against strategy output, inspect hand logs, and convert theory work into practical feedback and repetition.'],
    zh: ['与策略对战', '训练闭环', '直接针对策略输出做训练、查看 hand log，把理论研究转成可重复的反馈。'],
    ko: ['전략과 대결', '훈련 루프', '전략 출력과 직접 대결하고 핸드 로그를 검토하며 이론을 실제 피드백으로 전환합니다.'],
    ja: ['戦略と対戦', 'トレーニングループ', '戦略出力と対戦し、ハンドログを確認しながら理論を実戦的なフィードバックへ変えます。'],
    ru: ['Игра против стратегии', 'Тренировочный цикл', 'Тренируйтесь против стратегического вывода, просматривайте логи раздач и превращайте теорию в практическую обратную связь.'],
  },
  quickStart: {
    en: ['Quick Start', 'Fast entry', 'Filter by players, stacks, blinds, positions, and action classes to land on the exact postflop spot you want.'],
    zh: ['快速开始', '快速进入', '通过玩家数、筹码深度、盲注、位置和行动类别过滤，直接落到目标翻后场景。'],
    ko: ['퀵 스타트', '빠른 진입', '플레이어 수, 스택, 블라인드, 포지션, 액션 클래스로 원하는 포스트플랍 상황에 바로 도달합니다.'],
    ja: ['クイックスタート', '高速導入', '人数、スタック、ブラインド、ポジション、アクションクラスで絞り込み、目的のポストフロップ状況へすぐ移動します。'],
    ru: ['Быстрый старт', 'Быстрый вход', 'Фильтруйте по числу игроков, стекам, блайндам, позициям и типам действий, чтобы сразу попасть в нужный постфлоп-спот.'],
  },
  batch: {
    en: ['Batch Solver', 'Scale analysis', 'Queue multiple boards, monitor the run, and keep snapshots organized in one repeatable research flow.'],
    zh: ['批量求解', '规模分析', '批量加入多个 board、观察进度并整理快照，让研究过程更可重复。'],
    ko: ['배치 솔버', '대규모 분석', '여러 보드를 한 번에 넣고 진행 상황과 스냅샷을 한 흐름에서 관리합니다.'],
    ja: ['バッチ計算', '大規模分析', '複数のボードをまとめて投入し、進捗とスナップショットを 1 つの流れで管理できます。'],
    ru: ['Пакетный solver', 'Масштабирование анализа', 'Ставьте в очередь несколько бордов, отслеживайте процесс и упорядочивайте снимки в повторяемом исследовательском потоке.'],
  },
}
