export const siteConfig = {
  basePath: '/texassolver_gpu_page',
  productName: 'TexasSolver GPU',
  email: 'icybee@yeah.net',
  contactHref: 'mailto:icybee@yeah.net',
  discordHref: 'https://discord.com/invite/RtyD4vRy2e',
  githubHref: 'https://github.com/bupticybee/TexasSolverGPU',
  downloadHref: 'https://github.com/bupticybee/TexasSolverGPU/releases',
  tutorialHref: 'https://www.youtube.com/watch?v=jAI_yudEGJw&list=PLKQz8vKPRvhmWz8lOUZjeLo7GQyG2ebu-',
  screenshots: {
    logo: 'logo-mark.png',
    tree: 'tree_construction_page.png',
    quickStart: 'quick_start_page.png',
    nodeLock: 'node_lock_page.png',
    batch: 'batch_solving_page.png',
    play: 'play_against_strategy.png',
    study: 'study_page.png',
    practice: 'practice_page.png',
  },
}

export const localeLabels = {
  en: 'English',
  zh: '中文',
  ko: '한국어',
  ja: '日本語',
  ru: 'Русский',
}

export const localeOrder = ['en', 'zh', 'ko', 'ja', 'ru']

export const localizedContent = {
  en: {
    lang: 'en',
    title: 'TexasSolver GPU | GPU Poker Solver Workspace',
    description:
      'TexasSolver GPU is the world’s first GPU solver for poker, combining strategy study, decision practice, node locking, tree configuration, and batch solving in one workspace.',
    nav: { overview: 'Overview', features: 'Features', faq: 'FAQ', language: 'Language' },
    carousel: { previous: 'Previous product screenshot', next: 'Next product screenshot' },
    hero: {
      eyebrow: 'Completely free for personal use',
      title: 'The world’s first GPU solver for poker',
      description:
        'Unmatched GPU speed. Professional-grade strategy research. Study and practice strategy, then go deeper with tree configuration, node locking, and batch solving.',
      download: 'Download for Free',
      tutorial: 'Video Tutorial',
      discord: 'Join Discord',
      contact: 'Contact',
      platform: 'Windows Only',
      free: 'Free for Personal Use',
      claim: 'The world’s first GPU solver',
    },
    valuesTitle: 'The fastest Texas Hold’em study tool',
    valuesText: 'Study the full strategy, practice the decisions, and use GPU solving tools when you want to go deeper. And most importantly, it’s completely free.',
    values: [
      ['Study Complete Strategies', 'Follow action lines, inspect range composition, and understand how each available action is mixed.'],
      ['Practice Every Decision', 'Repeat important spots and measure strategy match, EV loss, and decision quality with immediate feedback.'],
      ['Explore With Node Locking', 'Adjust strategic assumptions visually, lock the behavior you want to test, and solve again.'],
      ['GPU-Powered Research', 'Build custom trees and solve multiple boards through one focused, batch-oriented workflow.'],
    ],
    featuresTitle: 'From strategy study to deep solver research',
    featuresText: 'Start with Study and Practice, then go deeper with tree configuration, node locking, and batch solving.',
    ecosystemTitle: 'Fits the way people actually study',
    ecosystemText:
      'TexasSolver GPU supports open data formats, readable data scripts, and range imports that make it easier to fit into surrounding study setups.',
    ecosystem: ['Open data formats', 'Readable data scripts', 'Range import support', 'Friendly to external workflows'],
    futureTitle: 'And this is only the beginning',
    futureText:
      'Behind TexasSolver GPU, we are already building even faster methods, deeper optimizations, and much more ambitious solver technology.',
    faqTitle: 'FAQ',
    faq: [
      ['What platform is supported?', 'The current release is built for Windows.'],
      ['Is it free for personal use?', 'Yes. TexasSolver GPU is completely free for personal use.'],
      ['Where should I go for questions or updates?', 'Use the Discord server for community discussion or contact directly by email.'],
      ['Can it fit into other tools?', 'Yes. TexasSolver GPU supports open data formats, readable scripts, and range imports.'],
    ],
    footer: { rights: 'All rights reserved.', github: 'GitHub', discord: 'Join Discord', contact: 'Contact' },
  },
  zh: {
    lang: 'zh-CN',
    title: 'TexasSolver GPU | GPU 德扑求解工作台',
    description:
      'TexasSolver GPU 是世界第一个德州扑克 GPU Solver，把策略研究、决策训练、Node Lock、树构建和批量求解整合在同一个工作台中。',
    nav: { overview: '概览', features: '功能', faq: '常见问题', language: '语言' },
    carousel: { previous: '上一张产品截图', next: '下一张产品截图' },
    hero: {
      eyebrow: '对个人完全免费',
      title: '世界第一个德州扑克 GPU Solver',
      description:
        '无可匹敌的 GPU 速度，专业级的策略研究能力。先学习和训练策略，再通过树构建、Node Lock 和批量求解深入研究。',
      download: '免费下载',
      tutorial: '视频教程',
      discord: '加入 Discord',
      contact: '联系我',
      platform: '仅支持 Windows',
      free: '对个人完全免费',
      claim: '世界第一个 GPU Solver',
    },
    valuesTitle: '最快的德州扑克学习工具',
    valuesText: '先理解完整策略，再训练每一个决策，并在需要时用 GPU 求解工具深入研究。最重要的是，它完全免费。',
    values: [
      ['研究完整策略', '沿行动线查看范围组成和各个动作的混合频率，理解策略为什么这样运行。'],
      ['训练每一个决策', '反复练习重要场景，通过策略匹配度、EV Loss 和错误等级获得即时反馈。'],
      ['用 Node Lock 深入验证', '可视化调整策略假设，锁定需要测试的行为，然后重新求解。'],
      ['GPU 驱动的研究流程', '构建自定义求解树，并在同一套批量工作流中处理多个 board。'],
    ],
    featuresTitle: '从策略学习到深度求解',
    featuresText: '从 Study 和 Practice 开始，再通过树构建、Node Lock 和批量求解进入更深的研究。',
    ecosystemTitle: '更贴近真实研究方式',
    ecosystemText: 'TexasSolver GPU 支持开放数据格式、可读取数据脚本和 range 导入，更容易接入你已有的研究流程。',
    ecosystem: ['开放数据格式', '可读取数据脚本', '支持导入 range', '方便接入外部工作流'],
    futureTitle: '而这还只是开始',
    futureText: '在 TexasSolver GPU 背后，我们已经在推进更快的方法、更深的优化，以及更激进的新一代求解技术。',
    faqTitle: '常见问题',
    faq: [
      ['支持什么平台？', '当前版本面向 Windows。'],
      ['对个人使用免费吗？', '是的，TexasSolver GPU 对个人完全免费。'],
      ['去哪里提问或获取更新？', '可以加入 Discord，或通过邮件直接联系。'],
      ['能和其他工具配合吗？', '可以，TexasSolver GPU 支持开放数据格式、可读取脚本和 range 导入。'],
    ],
    footer: { rights: '保留所有权利。', github: 'GitHub', discord: '加入 Discord', contact: '联系我' },
  },
  ko: {
    lang: 'ko',
    title: 'TexasSolver GPU | GPU 포커 솔버 워크스페이스',
    description:
      'TexasSolver GPU는 포커를 위한 세계 최초의 GPU 솔버로, 전략 학습과 의사결정 훈련, 노드 락, 트리 구성, 배치 솔빙을 하나의 작업 공간에 담았습니다.',
    nav: { overview: '개요', features: '기능', faq: 'FAQ', language: '언어' },
    carousel: { previous: '이전 제품 스크린샷', next: '다음 제품 스크린샷' },
    hero: {
      eyebrow: '개인 사용 완전 무료',
      title: '포커를 위한 세계 최초의 GPU 솔버',
      description:
        '비교할 수 없는 GPU 속도. 전문가급 전략 연구 기능. 전략을 학습하고 연습한 뒤 트리 구성, 노드 락, 배치 솔빙으로 더 깊이 탐구하세요.',
      download: '무료 다운로드',
      tutorial: '동영상 튜토리얼',
      discord: '디스코드 참여',
      contact: '문의하기',
      platform: 'Windows 전용',
      free: '개인 사용 완전 무료',
      claim: '세계 최초의 GPU 솔버',
    },
    valuesTitle: '가장 빠른 텍사스 홀덤 학습 도구',
    valuesText: '전체 전략을 이해하고 각 의사결정을 연습한 뒤, 필요할 때 GPU 솔빙 도구로 더 깊이 탐구하세요. 무엇보다도 완전히 무료입니다.',
    values: [
      ['전체 전략 학습', '액션 라인, 레인지 구성, 각 액션의 혼합 빈도를 함께 확인하세요.'],
      ['모든 의사결정 연습', '주요 스팟을 반복하고 전략 일치도, EV 손실, 판단 품질에 대한 즉시 피드백을 받으세요.'],
      ['노드 락으로 가설 검증', '전략 가정을 시각적으로 조정하고 테스트할 행동을 고정한 후 다시 해결합니다.'],
      ['GPU 기반 연구', '사용자 정의 트리를 구성하고 여러 보드를 하나의 배치 작업 흐름에서 해결합니다.'],
    ],
    featuresTitle: '전략 학습에서 심층 솔버 연구까지',
    featuresText: 'Study와 Practice로 시작하고 트리 구성, 노드 락, 배치 솔빙으로 더 깊이 탐구하세요.',
    ecosystemTitle: '실제 연구 방식에 잘 맞는 설계',
    ecosystemText: '오픈 데이터 포맷, 읽기 쉬운 데이터 스크립트, 레인지 가져오기를 통해 기존 연구 흐름과 자연스럽게 연결됩니다.',
    ecosystem: ['오픈 데이터 포맷', '읽기 쉬운 데이터 스크립트', '레인지 가져오기', '외부 워크플로 친화적'],
    futureTitle: '그리고 이것은 시작에 불과합니다',
    futureText: 'TexasSolver GPU 뒤에서는 더 빠른 방법론, 더 깊은 최적화, 그리고 훨씬 더 공격적인 차세대 솔버 기술이 계속 개발되고 있습니다.',
    faqTitle: 'FAQ',
    faq: [
      ['어떤 플랫폼을 지원하나요?', '현재 릴리스는 Windows용입니다.'],
      ['개인 사용은 무료인가요?', '네. TexasSolver GPU는 개인 사용 완전 무료입니다.'],
      ['질문이나 업데이트는 어디서 확인하나요?', '디스코드에 참여하거나 이메일로 직접 문의할 수 있습니다.'],
      ['다른 도구와 함께 쓸 수 있나요?', '네. TexasSolver GPU는 오픈 데이터 포맷, 읽기 쉬운 스크립트, 레인지 가져오기를 지원합니다.'],
    ],
    footer: { rights: '모든 권리 보유.', github: 'GitHub', discord: '디스코드 참여', contact: '문의하기' },
  },
  ja: {
    lang: 'ja',
    title: 'TexasSolver GPU | GPU ポーカーソルバーワークスペース',
    description:
      'TexasSolver GPU はポーカー向け世界初の GPU solver。戦略学習、意思決定の練習、Node Lock、ツリー構築、バッチ計算をひとつにまとめます。',
    nav: { overview: '概要', features: '機能', faq: 'FAQ', language: '言語' },
    carousel: { previous: '前の製品スクリーンショット', next: '次の製品スクリーンショット' },
    hero: {
      eyebrow: '個人利用は完全無料',
      title: 'ポーカー向け世界初の GPU solver',
      description:
        '比類のない GPU 速度。プロフェッショナルレベルの戦略研究機能。戦略を学び、練習した上で、ツリー構築、Node Lock、バッチ計算へと研究を深められます。',
      download: '無料ダウンロード',
      tutorial: 'ビデオチュートリアル',
      discord: 'Discord に参加',
      contact: 'お問い合わせ',
      platform: 'Windows 専用',
      free: '個人利用完全無料',
      claim: '世界初の GPU solver',
    },
    valuesTitle: '最速のテキサスホールデム学習ツール',
    valuesText: '戦略全体を理解し、意思決定を練習し、必要なときは GPU solver でさらに深く検証できます。そして何より、完全無料です。',
    values: [
      ['戦略全体を学習', 'アクションライン、レンジ構成、各アクションの混合頻度をまとめて確認できます。'],
      ['意思決定を反復練習', '重要なスポットを反復し、戦略一致率、EV ロス、判断品質の即時フィードバックを得られます。'],
      ['Node Lock で仮説を検証', '戦略上の仮定を視覚的に調整し、検証したい行動を固定して再計算できます。'],
      ['GPU 駆動の研究', 'カスタムツリーを構築し、複数のボードをひとつのバッチフローで計算します。'],
    ],
    featuresTitle: '戦略学習から深度な solver 研究まで',
    featuresText: 'Study と Practice から始め、ツリー構築、Node Lock、バッチ計算でさらに深く探究できます。',
    ecosystemTitle: '実際の研究スタイルにフィット',
    ecosystemText: 'オープンなデータ形式、読みやすいデータスクリプト、レンジのインポートにより既存の研究環境にも組み込みやすくなります。',
    ecosystem: ['オープンなデータ形式', '読みやすいデータスクリプト', 'レンジのインポート', '外部ワークフローと親和性'],
    futureTitle: 'そして、これはまだ始まりにすぎません',
    futureText: 'TexasSolver GPU の背後では、さらに高速な手法、より深い最適化、そして次世代の solver 技術をすでに開発し続けています。',
    faqTitle: 'FAQ',
    faq: [
      ['対応プラットフォームは？', '現在のリリースは Windows 向けです。'],
      ['個人利用は無料ですか？', 'はい。TexasSolver GPU は個人利用完全無料です。'],
      ['質問や更新はどこで確認できますか？', 'Discord に参加するか、メールで直接連絡できます。'],
      ['他のツールと連携できますか？', 'はい。TexasSolver GPU はオープンなデータ形式、読みやすいスクリプト、レンジのインポートをサポートします。'],
    ],
    footer: { rights: 'All rights reserved.', github: 'GitHub', discord: 'Discord に参加', contact: 'お問い合わせ' },
  },
  ru: {
    lang: 'ru',
    title: 'TexasSolver GPU | GPU рабочее пространство для покера',
    description:
      'TexasSolver GPU — первый в мире GPU solver для покера, объединяющий изучение стратегий, тренировку решений, node lock, настройку дерева и пакетные расчеты.',
    nav: { overview: 'Обзор', features: 'Функции', faq: 'FAQ', language: 'Язык' },
    carousel: { previous: 'Предыдущий скриншот продукта', next: 'Следующий скриншот продукта' },
    hero: {
      eyebrow: 'Полностью бесплатно для личного использования',
      title: 'Первый в мире GPU solver для покера',
      description:
        'Непревзойденная скорость GPU. Профессиональные возможности для исследования стратегии. Изучайте и тренируйте стратегию, а затем углубляйтесь в настройку дерева, node lock и пакетные расчеты.',
      download: 'Скачать бесплатно',
      tutorial: 'Видеоурок',
      discord: 'Войти в Discord',
      contact: 'Связаться',
      platform: 'Только Windows',
      free: 'Полностью бесплатно для личного использования',
      claim: 'Первый в мире GPU solver',
    },
    valuesTitle: 'Самый быстрый инструмент для изучения техасского холдема',
    valuesText: 'Изучайте стратегию, тренируйте каждое решение и используйте GPU solver для более глубокого анализа. И самое главное—это совершенно бесплатно.',
    values: [
      ['Изучение полной стратегии', 'Проходите по линиям действий, изучайте состав диапазона и частоты каждого доступного действия.'],
      ['Тренировка каждого решения', 'Повторяйте важные ситуации и получайте обратную связь по совпадению со стратегией, EV loss и качеству решения.'],
      ['Проверка гипотез через Node Lock', 'Визуально меняйте стратегические допущения, фиксируйте нужное поведение и выполняйте повторный расчет.'],
      ['Исследования на GPU', 'Стройте собственные деревья и решайте несколько бордов в одном пакетном процессе.'],
    ],
    featuresTitle: 'От изучения стратегии до глубоких solver-исследований',
    featuresText: 'Начните с Study и Practice, а затем углубляйтесь в настройку дерева, node lock и пакетные расчеты.',
    ecosystemTitle: 'Подходит для реального учебного процесса',
    ecosystemText: 'Открытые форматы данных, читаемые скрипты и импорт диапазонов помогают встроить TexasSolver GPU в существующие исследовательские процессы.',
    ecosystem: ['Открытые форматы данных', 'Читаемые скрипты данных', 'Импорт диапазонов', 'Подходит для внешних рабочих процессов'],
    futureTitle: 'И это только начало',
    futureText: 'За TexasSolver GPU уже стоят еще более быстрые методы, более глубокие оптимизации и гораздо более амбициозные solver-технологии следующего поколения.',
    faqTitle: 'FAQ',
    faq: [
      ['Какая платформа поддерживается?', 'Текущий релиз предназначен для Windows.'],
      ['Бесплатно ли это для личного использования?', 'Да. TexasSolver GPU полностью бесплатен для личного использования.'],
      ['Где задавать вопросы и следить за обновлениями?', 'Можно присоединиться к Discord или написать напрямую по email.'],
      ['Можно ли встроить в другие инструменты?', 'Да. TexasSolver GPU поддерживает открытые форматы данных, читаемые скрипты и импорт диапазонов.'],
    ],
    footer: { rights: 'Все права защищены.', github: 'GitHub', discord: 'Войти в Discord', contact: 'Связаться' },
  },
}

export const featureOrder = ['study', 'practice', 'tree', 'nodeLock', 'batch']

export const featureContent = {
  study: {
    en: ['Strategy Study', 'Ranges & action lines', 'Navigate every preflop and postflop branch, change board cards, inspect the 13×13 range grid, and compare action frequencies down to exact combos.'],
    zh: ['策略研究', '范围与行动线', '浏览每一条翻前和翻后分支，切换公共牌，查看 13×13 范围矩阵，并精确比较每个组合的行动频率。'],
    ko: ['전략 학습', '레인지와 액션 라인', '모든 프리플롭·포스트플롭 분기를 탐색하고 보드 카드를 바꾸며 13×13 레인지 그리드와 정확한 콤보별 액션 빈도를 비교하세요.'],
    ja: ['戦略学習', 'レンジとアクションライン', 'プリフロップとポストフロップの全分岐を追い、ボードを変更しながら 13×13 レンジとコンボ単位のアクション頻度を比較できます。'],
    ru: ['Изучение стратегии', 'Диапазоны и линии', 'Переходите по всем ветвям префлопа и постфлопа, меняйте карты борда, изучайте сетку 13×13 и сравнивайте частоты до точных комбинаций.'],
  },
  practice: {
    en: ['Decision Practice', 'Drills & feedback', 'Build and save drills, repeat the same decision, and get instant grades—best move, mixed action, inaccuracy, wrong move, or blunder—with strategy match and EV loss.'],
    zh: ['决策训练', '训练题与即时反馈', '创建并保存训练题，反复练习同一决策，立即获得最优、混合、不准确、错误或严重失误评级，同时查看策略匹配度和 EV Loss。'],
    ko: ['의사결정 연습', '드릴과 즉시 피드백', '드릴을 만들고 저장한 뒤 같은 결정을 반복하세요. 최선, 혼합 액션, 부정확, 오류, 치명적 실수 등급과 전략 일치도, EV 손실을 즉시 확인할 수 있습니다.'],
    ja: ['意思決定の練習', 'ドリルと即時評価', 'ドリルを作成・保存し、同じ判断を反復。最善、混合アクション、不正確、ミス、ブランダーの評価と、戦略一致率・EV ロスを即座に確認できます。'],
    ru: ['Тренировка решений', 'Упражнения и оценка', 'Создавайте и сохраняйте упражнения, повторяйте решения и сразу получайте оценку: лучший ход, смешанное действие, неточность, ошибка или грубая ошибка—вместе с EV loss.'],
  },
  tree: {
    en: ['Flexible Tree Configuration', 'Inputs & sizings', 'Set the board, pot, effective stack, both ranges, and separate flop, turn, and river bet and raise sizes—including all-in branches—from one screen.'],
    zh: ['灵活树构建', '参数与下注尺寸', '在一个界面中设置牌面、底池、有效筹码和双方范围，分别定义翻牌、转牌和河牌的下注与加注尺寸，并可加入 All-in 分支。'],
    ko: ['유연한 트리 구성', '입력값과 사이징', '한 화면에서 보드, 팟, 유효 스택, 양쪽 레인지를 설정하고 플롭·턴·리버의 벳과 레이즈 사이징, 올인 분기까지 각각 정의하세요.'],
    ja: ['柔軟なツリー構築', '入力とサイジング', 'ボード、ポット、有効スタック、両者のレンジと、フロップ・ターン・リバーごとのベット・レイズサイズをオールイン分岐まで 1 画面で設定できます。'],
    ru: ['Гибкая настройка дерева', 'Параметры и сайзинги', 'В одном окне задавайте борд, пот, эффективный стек, оба диапазона, размеры бетов и рейзов для флопа, терна и ривера, включая ветви all-in.'],
  },
  nodeLock: {
    en: ['Visual Node Lock', 'Exploit modeling', 'Edit action frequencies by hand class or exact combo, lock selected behavior, and re-solve the tree to measure how the optimal response changes.'],
    zh: ['可视化 Node Lock', '针对性模型', '按起手牌类别或精确组合修改行动频率，锁定选中行为并重新求解，直接观察最优应对如何变化。'],
    ko: ['비주얼 노드 락', '익스플로잇 모델링', '핸드 클래스나 정확한 콤보별로 액션 빈도를 수정하고 선택한 행동을 잠그며 트리를 다시 풀어 최적 대응이 어떻게 바뀌는지 확인하세요.'],
    ja: ['ビジュアル Node Lock', 'エクスプロイトモデリング', 'ハンドクラスまたは正確なコンボ単位でアクション頻度を編集し、選択した行動をロックして再計算。最適応答の変化を直接比較できます。'],
    ru: ['Визуальный Node Lock', 'Моделирование эксплойта', 'Меняйте частоты по классу рук или точной комбинации, фиксируйте выбранное поведение и пересчитывайте дерево, чтобы увидеть изменение оптимального ответа.'],
  },
  play: {
    en: ['Play Vs Strategy', 'Training loop', 'Train against strategy output, inspect hand logs, and convert theory work into practical feedback and repetition.'],
    zh: ['与策略对战', '训练闭环', '直接针对策略输出做训练、查看 hand log，把理论研究转成可重复的反馈。'],
    ko: ['전략과 대결', '훈련 루프', '전략 출력과 직접 대결하고 핸드 로그를 검토하며 이론을 실제 피드백으로 전환합니다.'],
    ja: ['戦略と対戦', 'トレーニングループ', '戦略出力と対戦し、ハンドログを確認しながら理論を実戦的なフィードバックへ変えます。'],
    ru: ['Игра против стратегии', 'Тренировочный цикл', 'Тренируйтесь против стратегического вывода, просматривайте логи раздач и превращайте теорию в практическую обратную связь.'],
  },
  quickStart: {
    en: ['Quick Start', 'Fast entry', 'Filter by players, stacks, blinds, positions, and action classes to land on the exact postflop spot you want.'],
    zh: ['快速开始', '快速进入', '通过玩家数、筹码深度、盲注、位置和行动类别过滤，直接落到目标翻后场景。'],
    ko: ['퀵 스타트', '빠른 진입', '플레이어 수, 스택, 블라인드, 포지션, 액션 클래스로 원하는 포스트플랍 상황에 바로 도달합니다.'],
    ja: ['クイックスタート', '高速導入', '人数、スタック、ブラインド、ポジション、アクションクラスで絞り込み、目的のポストフロップ状況へすぐ移動します。'],
    ru: ['Быстрый старт', 'Быстрый вход', 'Фильтруйте по числу игроков, стекам, блайндам, позициям и типам действий, чтобы сразу попасть в нужный постфлоп-спот.'],
  },
  batch: {
    en: ['Batch Solver', 'Multi-board solving', 'Queue multiple boards, set iterations and target exploitability, cap exported file size, monitor every job, and open completed results directly in the explorer.'],
    zh: ['批量求解', '多牌面求解', '一次排队多个 board，设置迭代次数和目标 exploitability，限制导出文件大小，实时监控每个任务，并直接在 Explorer 中打开完成的结果。'],
    ko: ['배치 솔버', '다중 보드 솔빙', '여러 보드를 한번에 대기열에 넣고 반복 횟수와 목표 exploitability, 내보낼 파일 크기를 설정하세요. 각 작업을 실시간으로 모니터링하고 완료된 결과를 Explorer에서 바로 열 수 있습니다.'],
    ja: ['バッチ計算', '複数ボードの一括計算', '複数のボードをキューに入れ、反復回数、目標 exploitability、出力ファイル容量を設定。各ジョブを監視し、完了結果を Explorer で直接開けます。'],
    ru: ['Пакетный solver', 'Расчет многих бордов', 'Ставьте в очередь несколько бордов, задавайте число итераций, целевую exploitability и лимит файла. Следите за каждой задачей и открывайте готовые результаты прямо в Explorer.'],
  },
}
